version: '3.7'
services: 
  alert:
    build: 
      context: .
      dockerfile: Dockerfile
    image: 'fastapi'
    container_name: alert
    volumes:
      - .:/app
    container_name: fastapi
    ports: 
      - 8000:8000
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks: 
      - app-network
    depends_on: 
      - mongo

  shinobi:
        image: fahad56/vms:1.0
        container_name: Shinobi
        environment:
          - PLUGIN_KEYS={"Tensorflow":"275f20d5b186421deb377c88bb826"}
          - SSL_ENABLED=false
        volumes:
          - ./db:/var/lib/mysql
        ports:
          - 8080:8080
        restart: unless-stopped
        networks:
          - app-network
  
  shinobiplugintensorflow:
        image: fahad56/vms-ai:1.3
        container_name: shinobi-tensorflow
        environment:
          - PLUGIN_KEY=275f20d5b186421deb377c88bb826
          - PLUGIN_HOST=Shinobi
        restart: unless-stopped
        networks: 
          - app-network

  mongo:
    image: mongo:3.6
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks: 
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: trudesk
      ME_CONFIG_MONGODB_ADMINPASSWORD: TruDesk1
      ME_CONFIG_BASICAUTH_USERNAME: trudesk
      ME_CONFIG_BASICAUTH_PASSWORD: TruDesk1
    networks: 
      - app-network
    depends_on:
      - mongo

  trudesk:
    image: fahad56/vms-ticketing:1.0
    restart: always
    container_name: ticketing
    ports:
      - 8118:8118
    volumes: 
      - ./images:/usr/src/trudesk/public/images
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
    networks: 
      - app-network
    depends_on:
      - mongo

networks: 
  app-network:
    driver: bridge

# version: '3.7'
# services: 
#   alert:
#     image: fahad56/vms-alert:1.1
#     container_name: Alerts
#     ports: 
#       - 8000:8000
#     command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
#     networks: 
#       - app-network
#     depends_on: 
#       - mongo
  
  # shinobi:
  #       image: fahad56/vms:1.0
  #       container_name: Shinobi
  #       environment:
  #         - PLUGIN_KEYS={"Tensorflow":"275f20d5b186421deb377c88bb826"}
  #         - SSL_ENABLED=false
  #       volumes:
  #         - ./db:/var/lib/mysql
  #       ports:
  #         - 8080:8080
  #       restart: unless-stopped
  #       networks:
  #         - app-network
  
  # shinobiplugintensorflow:
  #       image: fahad56/vms-ai:1.2
  #       container_name: shinobi-tensorflow
  #       environment:
  #         - PLUGIN_KEY=275f20d5b186421deb377c88bb826
  #         - PLUGIN_HOST=Shinobi
  #       restart: unless-stopped
  #       networks: 
  #         - app-network
  
#   trudesk:
#     image: fahad56/vms-ticketing:1.0
#     restart: always
#     ports:
#       - 8118:8118
#     environment:
#       NODE_ENV: production
#       TRUDESK_DOCKER: "true"
#       TD_MONGODB_SERVER: mongo
#       TD_MONGODB_DATABASE: trudesk
#     networks: 
#       - app-network
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo:3.6
#     container_name: mongo
#     restart: always
#     ports:
#       - 27017:27017
#     volumes:
#       - ./database:/data/db
#     networks: 
#       - app-network

#   mongo-express:
#     image: mongo-express
#     container_name: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: trudesk
#       ME_CONFIG_MONGODB_ADMINPASSWORD: Trudesk1
#       ME_CONFIG_BASICAUTH_USERNAME: trudesk
#       ME_CONFIG_BASICAUTH_PASSWORD: Trudesk1
#     networks: 
#       - app-network

# networks: 
#   app-network:
#     driver: bridge